Implemented Linting
neurotechuoft/BrainTag_2022 pull request #26
Opened 2020-01-09 20:23 UTC by PersonalCorrect

Implemented linting to ensure our code style is consistent.

To run linting, run
> npm run pretest

Also, verify that the application did not break due to these changes.

2020-01-12 20:09 UTC, dakotamcinnis commented
@PersonalCorrect The application is still working as expected. However, running "npm run pretest" is listing 256 errors & 0 warnings. Is this consistent with what you are seeing?

2020-01-12 21:53 UTC, dakmcinnis requested changes
We should ignore the folder: ..\BrainTag\brain-tag\build. I found these errors:



Users\Dakota\ReactProjects\BrainTag\brain-tag>npm run pretest

> brain-tag@0.1.0 pretest C:\Users\Dakota\ReactProjects\BrainTag\brain-tag
> npm install && eslint . --fix

npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.1.4 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

audited 905833 packages in 9.041s
found 5 vulnerabilities (2 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Dakota\ReactProjects\BrainTag\brain-tag\build\service-worker.js
  14:1   error  'importScripts' is not defined    no-undef
  16:1   error  'importScripts' is not defined    no-undef
  26:1   error  'workbox' is not defined          no-undef
  34:1   error  'workbox' is not defined          no-undef
  36:1   error  'workbox' is not defined          no-undef
  36:41  error  'workbox' is not defined          no-undef
  38:29  error  Unnecessary escape character: \/  no-useless-escape
  38:38  error  Unnecessary escape character: \/  no-useless-escape

C:\Users\Dakota\ReactProjects\BrainTag\brain-tag\build\static\js\2.fceef125.chunk.js
  1:1       error  This line has a length of 224909. Maximum allowed is 120                   max-len
  1:77      error  Unexpected comma in middle of array                                        no-sparse-arrays
  1:703     error  Empty block statement                                                      no-empty
  1:772     error  Empty block statement                                                      no-empty
  1:1719    error  Empty block statement                                                      no-empty
  1:7819    error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  1:8093    error  't' is defined but never used                                              no-unused-vars
  1:8891    error  'r' is a function                                                          no-func-assign
  1:9084    error  'r' is a function                                                          no-func-assign
  1:9316    error  'o' is a function                                                          no-func-assign
  1:9695    error  'r' is a function                                                          no-func-assign
  1:24630   error  'o' is defined but never used                                              no-unused-vars
  1:24632   error  'i' is defined but never used                                              no-unused-vars
  1:31455   error  Unnecessary escape character: \/                                           no-useless-escape
  1:32699   error  Empty block statement                                                      no-empty
  1:32762   error  'XDomainRequest' is not defined                                            no-undef
  1:32785   error  Empty block statement                                                      no-empty
  1:32882   error  Empty block statement                                                      no-empty
  1:34384   error  't' is defined but never used                                              no-unused-vars
  1:34386   error  'n' is defined but never used                                              no-unused-vars
  1:35582   error  't' is defined but never used                                              no-unused-vars
  1:35584   error  'n' is defined but never used                                              no-unused-vars
  1:36327   error  't' is defined but never used                                              no-unused-vars
  1:36535   error  't' is defined but never used                                              no-unused-vars
  1:36563   error  Unnecessary escape character: \/                                           no-useless-escape
  1:36668   error  Unnecessary escape character: \/                                           no-useless-escape
  1:36707   error  Unnecessary escape character: \/                                           no-useless-escape
  1:36717   error  Unnecessary escape character: \/                                           no-useless-escape
  1:36745   error  Unnecessary escape character: \/                                           no-useless-escape
  1:37321   error  't' is defined but never used                                              no-unused-vars
  1:38770   error  'e' is defined but never used                                              no-unused-vars
  1:38802   error  'e' is defined but never used                                              no-unused-vars
  1:38903   error  'e' is defined but never used                                              no-unused-vars
  1:38998   error  't' is defined but never used                                              no-unused-vars
  1:39451   error  't' is defined but never used                                              no-unused-vars
  1:41967   error  't' is defined but never used                                              no-unused-vars
  1:47271   error  'n' is defined but never used                                              no-unused-vars
  1:47273   error  'r' is defined but never used                                              no-unused-vars
  1:49136   error  't' is defined but never used                                              no-unused-vars
  1:49138   error  'n' is defined but never used                                              no-unused-vars
  1:49541   error  't' is defined but never used                                              no-unused-vars
  1:50736   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  1:53532   error  't' is defined but never used                                              no-unused-vars
  1:53534   error  'n' is defined but never used                                              no-unused-vars
  1:54730   error  't' is defined but never used                                              no-unused-vars
  1:54833   error  't' is defined but never used                                              no-unused-vars
  1:55186   error  '__REACT_DEVTOOLS_GLOBAL_HOOK__' is not defined                            no-undef
  1:55233   error  '__REACT_DEVTOOLS_GLOBAL_HOOK__' is not defined                            no-undef
  1:57982   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  1:61796   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  1:63000   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  1:63097   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  1:63357   error  'r' is defined but never used                                              no-unused-vars
  1:63359   error  'o' is defined but never used                                              no-unused-vars
  1:63361   error  'i' is defined but never used                                              no-unused-vars
  1:63363   error  'a' is defined but never used                                              no-unused-vars
  1:63365   error  'l' is defined but never used                                              no-unused-vars
  1:63367   error  'u' is defined but never used                                              no-unused-vars
  1:63532   error  'e' is defined but never used                                              no-unused-vars
  1:63534   [...]

2020-01-12 22:18 UTC, PersonalCorrect commented
Dev Tests:
- Ran "npm run build"

**Before changes**
- Ran "npm run pretest" => many errors

** After changes**
- Ran "npm run pretest" => no errors

2020-01-26 19:09 UTC, dakmcinnis approved these changes

2020-01-26 19:09 UTC, merged