Added real time line plot
neurotechuoft/BrainTag_2022 pull request #6
Opened 2019-11-03 20:08 UTC by SamarthAP

Connected to socket and displays the real time plot using CanvasJS which I found to be the only library capable of handling large amounts of data. It's pretty CPU intensive and we might need to find ways to optimize further. 
Also currently CanvasJS is a trail version but they provide free licences for students which I have inquired about.

2019-11-03 22:18 UTC, DiademShoukralla requested changes
This looks really good! I want to merge into development, but before I do, could you please refactor the changes into folders/components? 
Specifically, 
- src/
-- assets/
-- App/
--- App.css
--- App.js
--- App.test.js
-- DynamicLineGraph/
--- DynamicLineGraph.js
--- DynamicLineGraph.css

etc

2019-11-08 06:44 UTC, SamarthAP commented
Folder structure has been refactored. Also edited the dummy server to also emit time.

2019-11-09 22:54 UTC, DiademShoukralla approved these changes

2019-11-09 22:54 UTC, PersonalCorrect commented
Thanks for the hard work!! Looks good :)

2019-11-09 22:55 UTC, merged